### ISSUE TITLE
null 처리를 대충 넘기면 안될 것 같습니다

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#101]
- 무분별한 isFiltered 사용
- 무분별한 && 사용
- 무분별한 != null 사용

지금은 Feature 개발 단계라 그냥 대충 타입 좁히고 넘어가긴 하는데, 나중에 리팩토링할 때는 확실히 봐야 할 것 같습니다. 

nullable 한 타입이 있는 경우에는 백엔드에 이유를 물어보고 적절히 처리해야 합니다.

**Comment by jpham005** [comment]
그렇게 생각하신 이유나 사례를 주시면 더 좋을 것 같습니다.

**Comment by yoopark** [comment]
https://github.com/42Statistics/42Stat-Backend/issues/208

graphql 상의 문제라고 하니 filter 하지 말고 그냥 assertion 하세요
