### ISSUE TITLE
반응형 Dashboard 구조 논의

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#13]
> 그냥 현재 생각하고 있는 문제 기록용으로 적습니다 ㅎㅎ

현재 짜려던 로직은 다음과 같습니다. 

**Dashboard를 줄마다 DashboardRow 컴포넌트로 나눈다.**
  - 이유 : Desktop의 경우 한 줄에 3개 들어갈 때와 4개 들어갈 때의 높이가 다르기 때문에 구분 필요
  - (Mobile의 경우 굳이 만들자면 전체를 하나의 Grid로 설정이 가능함.  작은 요소가 1개, 중간 요소가 2개, 8개 차지하도록)

![Image](https://user-images.githubusercontent.com/61629480/226189354-f5c95c74-1208-4c0d-8bea-f38c37b8fc05.png)

![Image](https://user-images.githubusercontent.com/61629480/226189317-4f5f9a60-33bf-4762-beef-6bcfcc869576.png)

이렇게 DashboardRow로 나누고 너비가 줄어들면 DashboardItem의 너비가 줄어드는 방식으로 제작하려 했었습니다. 

https://user-images.githubusercontent.com/61629480/225847951-131fa9e4-6194-4e8e-9da3-0d0259d48137.mov

위 영상에서도 볼 수 있듯이 Mobile로 바뀌기 직전 구간은 너무 좁아져서 Tablet UI (NavBar에 아이콘만 표시하는 방식으로)를 만들려고 했습니다만.... 대시보드 반응형을 구현한 다른 예시들을 보다보니 이 방식이 직관적이지 못하다는 걸 깨달았습니다. 

Google Analytics의 반응형 예시

https://user-images.githubusercontent.com/61629480/226190195-e4c75c55-687b-4735-8ed4-d70804f10973.mov

1. DashboardItem의 너비와 높이는 Mobile <-> Desktop 전환을 제외하고는 고정이어야 한다. 
2. Mobile <-> Desktop 전환이 아닌 경우에는 아래 Google Analytics의 예시처럼 **좌우 margin을 줄이거나, Flex-Wrap처럼 오른쪽 요소가 아래로 타고 내려오는 로직**을 택해야 한다. 

허허.. 고민이 되는 지점이 DashboardRow 로직에서는 Flex-Wrap처럼 내려오는게 사실상 불가능하다는 점입니다. 
Grid 사용이 처음이라 몰라서 더 찾아보면 나올 수도 있겠지만, 
1. 일반화 가능한 로직을 찾거나
2. Flex-Wrap은 그냥 포기하고 태블릿 정도 구간에는 Tablet UI를 별도로 제작하거나
3. Flex-Wrap이 가능해지도록 Dashboard 쪽 Figma 디자인 수정 (아마 너비는 상관 없는데, 요소별 높이는 다 같아야 할 듯)

중 하나를 택해야 하는 상황입니다. 

제 현재 생각은 1은 현 상황에선 못 찾겠고, 3은 최대한 뒤로 미루고 싶어서 Flex-Wrap처럼 되는 걸 포기해야 할 것 같습니다. 

---

음... 생각해보니 Tablet UI를 만들 필요 없이 Dashboard가 뭉개지는 구간에는 배치만 다르게 해도 되겠군요!

- 42 Intra : 대시보드의 모든 요소의 크기가 같아서 반응형으로 Wrap 가능
- Google Analytics : Flex-Wrap을 사용하면서 요소의 너비와 높이 모두 다름. Flex Item 들을 전부 absolute로 설정한 뒤 상황(어느 위치에 있는지)에 따라 모두 분류하고 top: 528px, left:672px 등등을 사용하면서 전부 다 강제로 배치... 오잉?? (gap을 쓴게 아님)

**Comment by jpham005** [comment]
Google Analytics 는 하나씩 배치해놨다는 걸까요? ㄷㄷ
아무래도 큰 회사일수록 frontend / markup / design 다 따로 있으니 그런 노력이 가능한걸지도....

개인적으론 Grid 를 사용하지 않고 FlexBox 로 해결해보는 건 어떨까 싶긴 하네요.

**Comment by yoopark** [comment]
> Google Analytics 는 하나씩 배치해놨다는 걸까요? ㄷㄷ 아무래도 큰 회사일수록 frontend / markup / design 다 따로 있으니 그런 노력이 가능한걸지도....
> 
> 개인적으론 Grid 를 사용하지 않고 FlexBox 로 해결해보는 건 어떨까 싶긴 하네요.

내부에서 수식이 있는건지는 모르겠는데, CSS 뜯어보면 요소마다 다 top, left px이 적혀 있어서... ㅋㅋㅋ 보고 깜짝 놀랐습니다.

**Comment by yoopark** [comment]
음... 아무리 생각해봐도 생각이 안나네요. 
다른 대시보드 디자인들 보니까 제 원래 영상대로 (요소의 width를 좌우 꽉 채우는 로직) 구현하신 예시들도 몇몇 보이더라구요...

FlexWrap을 사용해서 반응형을 처리하려면 무조건 요소의 크기를 다 동일하게 맞춰야 할 것 같습니다. (42 Intra 처럼)
그래도 원래 만든 디자인이 나름 예뻐서 또 수정하긴 조금 아깝고, 저런 CSS는 Flex보다는 Grid가 확실히 편해서 Grid로 그냥 가겠습니다.

Google Analytics의 경우 한 칸에 요소의 크기가 2개 or 3개라서 좌우 마진이 있고 width를 고정으로 할 수 있었던 건데, 저희는 그것보다 내용이 많아서 좌우를 비우는 것보다 그냥 채우는 방식이 낫겠다는 생각이 들었습니다. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61629480/226513951-6a2517d4-f586-4d7e-94eb-18e57bc6df82.png">

뭐... 사실 좌우를 채우냐 비우냐는 큰 논의거리는 아니고, 금방 수정할 수 있어서 일단 채우는 방식으로 짜겠습니다. 

그래서 제 생각에는 그냥 DashboardRow 로직 그대로 쓰고, Sidebar 쪽을 태블릿 크기에 맞게 하나 더 만드는 방식으로 해서 한번 진행해보겠습니다. 아마 태블릿 전용으로 Sidebar의 크기를 대폭 줄이면 나름 모바일 될 때까지 요소가 크게 짜부되진 않을 것 같아요 🤖

**Comment by yoopark** [comment]
ㅎㅎ 이슈 닫겠습니당
