### ISSUE TITLE
React Chart 라이브러리 결정

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#14]
## 기준
- 기존 기획에 있던 그래프를 모두 만들어낼 수 있는가?
- 예쁜가?
- 빠른가?

## 후보
> 아래 링크들은 모두 메인 페이지가 아닌 차트 예시 페이지입니다. 
- [Recharts](https://recharts.org/en-US/examples)
- [nivo](https://nivo.rocks/area-bump/)
- [react-chartjs-2](https://react-chartjs-2.js.org/examples/vertical-bar-chart)
- [apex charts](https://apexcharts.com/react-chart-demos/)
- [Victory](https://formidable.com/open-source/victory/gallery) : 제일 예쁘긴 한데 최근 몇달 push 기록도 없고 관련 포스팅도 별로 없어서 포기
- Visx : 디자인이 차트가 아닌데..? 너무 예술인데
- React Vis : 너무 안 예쁨

## 비교

1. https://okky.kr/questions/750300

d3는 svg, chartjs는 canvas를 이용하기 때문에 느낌이 다름.
화면에 뿌려줘야 할 오브젝트가 많다면, 차트를 주로 보기만 하는 용도라면 chartjs(react-chartjs-2) 사용
보여준 차트에서 보편적이지 않는 인터렉션 요소를 추가해야한다면 d3(Recharts, nivo) 사용

2. https://medium.com/react-courses/react-charts-built-on-d3-what-should-you-pick-rechart-visx-niv-react-vi-or-victory-adc64406caa1
Rechart, nivo, apex charts, Victory, Visx -> react-chartjs-2 빼고는 다 D3 활용

nivo는 홈페이지에서 커스텀해서 만들어두면 코드로 가져올 수 있어서 꽤 편리할 듯?
그런데 줄무늬 있는 디자인이 좀 별론데.

Victory 다음으로 디자인은 apex charts가 제일 예쁜듯.

챗지피티 추천 : ApexCharts (빠른 렌더링, 커스텀이 Recharts보다 잘됨)

**Comment by yoopark** [comment]
제가 예전에 찾아봤을 땐 1순위 Apex Charts, 2순위 Victory인데 한번 보시고 Issue에 올려주세요! @lev-Zero

**Comment by lev-Zero** [comment]
예제코드와 홈페이지 설명을 살펴본 결과 Apex Chart가 더 나을거 같습니다.
근거는
1. 커스터마이징 가능한 것과 별개로 디폴트 디자인이 우리 프로젝트 느낌과 비슷하다
2. 옵션을 훨씬 다양하게 넣어서 사용할 수 있다. (apex가 styled라면 victory는 chakra느낌)
3. 요팍님이 언급한 대로 참고자료가 apex쪽이 더 많은것 같다

apex로 가시죠옹~

**Comment by lev-Zero** [comment]
프론트끼리만 논의해서 성급하게 결정한 것 같아 보일 수 있기에 추가 자료를 첨부하여 설명글 남깁니다.

아래 사진은 victory와 apex를 이용해서 동일한 데이터를 가지고 기본 틀만 이용하여 차트를 출력한 모습입니다.
<img width="652" alt="Screenshot 2023-03-22 at 2 39 38 PM" src="https://user-images.githubusercontent.com/98072928/226814006-d2a9e4da-6ce3-4cdf-9280-dd54068aa634.png">

그리고 아래는 그러한 동일한 데이터를 차트로 표현하기 위해 넘겨주어야하는 코드화된 데이터의 모습입니다.
1. Victory
<img width="399" alt="Screenshot 2023-03-22 at 2 37 24 PM" src="https://user-images.githubusercontent.com/98072928/226814297-edde3b03-9f5d-40da-a39a-7ae6fbc96e75.png">

2.Apex
<img width="663" alt="Screenshot 2023-03-22 at 2 37 33 PM" src="https://user-images.githubusercontent.com/98072928/226814627-1e2d4e63-a016-4659-a7ba-7345d4767c61.png">
<img width="520" alt="Screenshot 2023-03-22 at 2 55 27 PM" src="https://user-images.githubusercontent.com/98072928/226814756-98a6025f-8f6a-4afc-bfaa-7ba77a81d03f.png">

결과적으로 말씀드리자면 저는 apex라이브러리를 이용하고 싶습니다.
이유는 다음과 같습니다.


### **1. 코드 간결성**
JSX로 컴포넌트를 리턴하는 부분에서도 Apex가 간결하고
props로 넘겨주는 데이터의 형식도 apex가 가독성이 좋습니다.


그리고 여러개의 데이터를 중첩시켜 표현할 경우(다층 bar그래프 등)에 apex의 경우에는 데이터의series를 여러개 선언하면 되지만 

victory의 경우에는 여러개의victory컴포넌트를 JSX로 선언하여 return문 안에서 중첩시켜야 합니다.


### **2. 강력한 기본 기능**
아울러 apex차트의 경우 기본 애니메이션과 1번쨰 사진에서 확인할 수 있는 마우스 토글을 통한 확대 및 차트 이미지 다운로드 기능을 제공하고 있습니다.

동일한 기능을 victory에서도 구현할 수 있지만 추가적인 작업을 진행해야 한다는 부분에서 apex가 보다 편리한 것 같습니다.


이와 같은 이유로 저는 apex를 저희 chart라이브러리로 선정하고싶은데 다른 의견 있으시면 코멘트 부탁드립니다.

**Comment by yoopark** [comment]
오호.. 둘다 해보셨다니 수고하셨습니당
오우 Victory 차트 안에 axis 정보를 컴포넌트화하는군요... axis를 컴포넌트화하는건 약간 비직관적이긴 하네요
Apex options 부분에서 여러 차트에서 자주 쓰는 axis를 따로 빼서 관리하는게 더 직관적인 것 같습니다
Apex ㄱㄱ

**Comment by yoopark** [comment]
#27 에서 이어 논의하겠습니다
