### ISSUE TITLE
날짜 계산 시 작은 값에서 큰 값을 뺄 때 생기는 문제

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Frontend#152]
날짜를 계산할때 Math.floor 를 사용하고 있는데, 이런 경우 음수값이 들어가게 되면 날짜 표기가 이상해보이는 것 같습니다.
Math.floor 는 항상 자신보다 작은 정수를 찾기 때문에... (ex. Math.floor(-0.01) => -1)
음수값이 나오게 되면 실제로 경과한 시간보다 하루 더 지난 것 처럼 보이게 되는 문제가 있네요.
ex. 오늘 어떤 과제를 통과함 => 프론트에선 1일 전 통과한 것으로 표기되는 중

따라서 이를 floor 와 abs 의 조합으로 해결하기보단, 애초에 큰쪽에서 작은쪽을 잘 빼도록 해야할 것 같습니다.

**Comment by jpham005** [comment]
일단 확인된 사용처는 persoanl general 의 team 정보를 보여주는 곳 입니다.

**Comment by yoopark** [comment]
넵 수정하겠습니당 ㅎㅎ 음수 floor 케이스가 있군요..
