### ISSUE TITLE
Safari에서 배경 이미지 로딩이 안됨

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#195]
<img width="1572" alt="image" src="https://github.com/42Statistics/42Stat-Frontend/assets/61629480/b0c7ca5b-a23d-427f-8c38-259faf0dd0a1">

이미지 캐싱 관련 문제일 수 있음.

**Comment by yoopark** [comment]
- #144

**Comment by jpham005** [comment]
#237 에서 해결이 된 것으로 보이는데, 확인 후 조치 부탁드립니다.

**Comment by yoopark** [comment]
<img width="772" alt="image" src="https://github.com/42Statistics/42Stat-Frontend/assets/61629480/5690a8c3-d171-4d41-a6db-9523652e768b">

이 배경은 #237 에서 오는 게 아니라서.. 어떻게 해결하면 좋을까요?

**Comment by jpham005** [comment]
아직 원인을 모르는건가요?
