### ISSUE TITLE
Refresh Token 없는 상태로 새로고침 또는 Url 직접 접근 시 /home으로 강제 리다이렉션

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#204]
- 이전에 jaham님이 올렸던 **profile page 를 url 을 통해 바로 접근하면 빈 화면만 나오는 문제** 이슈와 연결된 내용입니다. 
- 빈 화면이 나오는 문제는 해결했으나, 이제는 home으로 강제로 리다이렉션되는 버그가 있습니다. 

## 오류 발생 로직
1. 페이지를 이동할 때는 401 Interceptor가 잘 작동하여 Refresh Token을 갱신해줍니다. 
2. 반면, 새로고침 또는 Url 직접 접근 시에는 첫 요청에서 401 Interceptor가 작동하지 않아 `401 Unauthorized` Apollo Error가 그대로 Result로 출력됩니다. 따라서 AuthGuard에 걸려 `/`으로 리다이렉션됩니다. 
3. 이 경우, `/` 에서 NoAuthGuard에서 재요청하며, 이때는 401 Interceptor가 정상 작동하여 `/home`으로 리다이렉션되어 발생하는 결과임을 확인하였습니다. 

- **401 Interceptor에서 Error Catching 하는 로직에 문제가 있을 것으로 생각됩니다.** 
- 아마 새로고침 또는 직접 접근시에는 다른 지점에서 401 에러가 잡히며, 그곳의 조건을 추가해줘야하는게 아닐지 추측하고 있습니다.

**Comment by yoopark** [comment]
이렇게 하면 해당 이슈는 고쳐지는데, 42로 로그인했을 때 자꾸 400 에러가 뜨는 다른 문제가 발생하네요... 일단 Reopen 하겠습니다.

**Comment by jpham005** [comment]
@yoopark 무조건 발생하는건가요?
재현 방법 알려주시면 확인해볼게요.

**Comment by yoopark** [comment]
@jpham005 localhost에서 돌리면 구글 로그인은 잘 되는데, 42 로그인을 하면 400 Response(유효하지 않은 Refresh Token)가 반환됩니다. 혹시 그 현상 없이 잘 되시나요?

**Comment by jpham005** [comment]
네 그냥 되고있던지라...

**Comment by yoopark** [comment]
한번 그 상태로 stat.42seoul.kr 에 올려보겠습니다!
