### ISSUE TITLE
cdn coalition mark CORS

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#237]
<img width="601" alt="image" src="https://github.com/42Statistics/42Stat-Frontend/assets/61629480/67896c7e-c891-43b2-8eeb-8d0ef9277268">

**Comment by yoopark** [comment]
- 코알리숑 마크
- 코알리숑 배경
- LandingPage 배경

cdn으로 할 것.

**Comment by yoopark** [comment]
#195

**Comment by jpham005** [comment]
이거 확인해보니, 일단 백엔드에서 전달해주는 url 이 잘못된 부분이 있어 수정이 필요하고,
cors 관련해선 해당 부분 수정되고 확인 해볼게요.

**Comment by jpham005** [comment]
@yoopark 
url 수정한 상태고, 사진의 오류가 발생하는 상황 알려주시면 확인해보겠습니다.

**Comment by yoopark** [comment]
@jpham005 

사진의 오류는 localhost로 접속 시에 나타나고, stat.42seoul.kr 로 접속했을 때에는 정상으로 확인됩니다. 

현재 `http://localhost:8080` 에서 작업 중입니다. 

coalition url 바꾼 이후로는 fallback 되지 않고 cdn 이미지로 잘 나옵니다.

**Comment by yoopark** [comment]
tigCountPerCoalitionByDateTemplate 의 coalition에서는 코알리숑 로고 주소로 cdn.intra.** 가 오는 것 같은데 확인해주실 수 있을까요?

**Comment by jpham005** [comment]
네 해당 부분은 백엔드에서 그냥 intra 의 링크를 주고 있었던게 맞네요.
이전 url 문제와 함께 main 에 병합 될 예정 입니다.

**Comment by jpham005** [comment]
그리고 localhost 에서 오류 발생하는 부분에 대해선,
1. 일단 크롬에선 재현이 안되고... 
2. 배포판에선 상관 없으니 괜찮을 것 같긴 하네요.

**Comment by jpham005** [comment]
해당 이슈는 이후 문제가 다시 발생하면 보는 것으로 하겠습니다.
