### ISSUE TITLE
beginAt 계산 시 음수가 나올 수 있는 문제

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Frontend#294]
새로 들어오신 분들 아직 시작일이 아니라 계산에 문제가 있군요. 절대값으로 나오는 걸로 보이네요....

![Image](https://github.com/42Statistics/42Stat-Frontend/assets/76723089/7d4c4246-abce-441e-982c-d033167a8041)

**Comment by yoopark** [comment]
@jpham005 새로 들어오신 분 인트라 아이디를 알 수 있을까요?

**Comment by jpham005** [comment]
hyunjunl

**Comment by yoopark** [comment]
close by #296
