### ISSUE TITLE
내 정보 TeamInfoTable에서 팀명이 너무 긴 경우 overflow 처리

### ISSUE THREAD

**Issue by ElApostles** [42Statistics/42Stat-Frontend#295]
[현재 상태]
참고: https://stat.42seoul.kr/profile/hdoo/general

<img width="1498" alt="Screen Shot 2023-09-22 at 9 42 39 PM" src="https://github.com/42Statistics/42Stat-Frontend/assets/72256725/a1eefc64-4717-4ed5-9486-ef8ac7ce4b72">

[대충 고친 부분]
<img width="1549" alt="Screen Shot 2023-09-22 at 9 41 30 PM" src="https://github.com/42Statistics/42Stat-Frontend/assets/72256725/9e1381d6-519d-46fe-a010-7c6eabd9887f">

해당 태그의 css에 overflow와 text-overflow옵션 넣었습니다.  코드 수정해서 풀리퀘 넣고싶었는데, 저 태그만 바꾸는 방법도, 적용하는 방법도 잘 모르겠더라구요 하하

**Comment by yoopark** [comment]
이슈 감사합니다! 최신 버전의 Safari, Chrome에서는 정상적으로 작동하나, 이전 버전에서 발생하는 문제처럼 보이네요.

**Comment by ElApostles** [comment]
아 저는 파이어폭스 씁니다 ㅋㅋㅋ 그래서 다르게 보였나보네요

**Comment by yoopark** [comment]
Firefox에서, jiychoi의 경우에도 같은 버그가 발생합니다. 

![Image](https://github.com/42Statistics/42Stat-Frontend/assets/61629480/4a8fe4fd-5160-49d8-b291-6448a8dd5c43)

팀 페이지 제목에서는 jkong, jiychoi 둘 다 잘 나오는 것으로 확인하였습니다.
