### ISSUE TITLE
FE 프로젝트 스캐폴딩

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#3]
- [x] 페이지 path 정해서 React Route Dom 이용하여 라우팅
- [x] zustand / jotai 비교해서 뭘로 할지 정하기
- [x] 어느정도 손에 익었으면 본 레포에 기본적으로 스캐폴딩
- [x] GraphQL으로 정보 받는 법 익히기
- [x] 테스터, GraphQL mock 관련 알아보기
- [x] `.eslintrc.json` 작성하기
- [x] 어느정도 스캐폴딩 되면 Fork 받아 개인 레포에서 작업하기

**Comment by jpham005** [comment]
react query도 공부하기!

**Comment by yoopark** [comment]
# Path

- /(로그인 안 되었을 때) : LoginPage
- /(로그인 되었을 때) : HomePage
- /total : TotalPage
- /user/{username} : UserPage
- help : HelpPage
- /setting : SettingPage

**Comment by yoopark** [comment]
상태관리는 그냥 zustand 할게요 ㅎㅎ 별 차이 없는 것 같아서..
