### ISSUE TITLE
차트/컨벤션/겹치는 구조 리팩토링

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#30]
- [x] 차트 옵션들 리팩토링
- [x] Dashboard 내부 map 구조가 페이지마다 동일하므로 빼도 됨 #31
- [x] 데이터 타입 변수명과 컴포넌트 변수명이 충돌할 때(ex-DashboardItem)의 컨벤션 마련 -> 잠정적으로 `~Type`. 변동 가능
- [x] import 순서 컨벤션 마련하여 수정 [5b5470](https://github.com/42Statistics/42Stat-Frontend/commit/5b5470b96e12e3e05c59e01c1b3d7a171b823de0)
- [x] @emotion/styled css 순서 컨벤션 마련하여 수정 [5b5470](https://github.com/42Statistics/42Stat-Frontend/commit/5b5470b96e12e3e05c59e01c1b3d7a171b823de0)
- [ ] atom 파일 관리 방식 결정(현재는 기존 zustand에서의 utils/stores 자리와 똑같이 utils/atoms에 있음) 방법. 기존 42Stat 프로젝트는 components의 hooks 폴더 느낌으로 atoms 폴더가 있었음. 만약 utils/atoms에 모아서 관리할 거라면 atoms에도 index.tsx를 만들어 한꺼번에 import할 수 있도록
- [x] 폴더를 만들었지만 그 속에 index.tsx 하나만 있는 파일들은 사실상 그냥 Desktop.tsx 처럼 만들어도 무방함. 확실한 아이들은 밖으로 빼기 #31
- [ ] type 들 중에 일반적으로 쓸만한 것들은 utils/types 로 옮겨놓기
- [ ] eslint 제대로

**Comment by yoopark** [comment]
- [ ] (어느정도 체계 정립되면) 이후 개발할 사람들을 위해 컨벤션 상세하게 기록
- [ ] 파일 구조 설명하는 글? 주석? 적어두는 것도 좋을 듯

**Comment by lev-Zero** [comment]
현재 차트 내부 코드 중에서.
사용 할 여지가 있는 부분들은 주석으로 남아있습니다.
저도 그러겠지만, 리팩토링 할때 나중에 쓸 수있는 옵션들임을 고려해서 수정부탁드립니다!

**Comment by yoopark** [comment]
오호 미리 말씀해주셔서 감사합니다 ㅎㅎ 주석 부분도 최대한 살리겠습니다

**Comment by yoopark** [comment]
오늘 저녁에 간단한 파일명 리팩토링할 계획입니다. 

index.tsx
Desktop.tsx
Mobile.tsx
위의 파일명은 파일 탐색할 때 직관적이지 못하다는 문제가 있어서 다음의 방식으로 변경하겠습니다.

index.tsx -> Component.tsx 로 바꾼 뒤 index.ts에서 묶어서 import
Desktop.tsx -> DesktopComponent.tsx

**Comment by yoopark** [comment]
- atoms, types 정리 -> 이후 검색/인증로직 들어와야 의미있을 것 같아 이후 진행하겠습니다. 
- 파일 구조 설명하는 글, 주석 -> 지금 적어봤자 바뀔 가능성이 많아서 조금 더 정착되면 작성하겠습니다.
