### ISSUE TITLE
나와비교 intra사진 없는사람끼리 비교

### ISSUE THREAD

**Issue by 42sungwook** [42Statistics/42Stat-Frontend#307]
두사람 모두 intra 사진이 없을 때 누가 자신인지 직관적으로 알기 힘든 문제가 있습니다!

<img width="770" alt="Screen Shot 2023-10-11 at 5 18 19 PM" src="https://github.com/42Statistics/42Stat-Frontend/assets/106149304/e46587c8-0b34-4c09-a42d-04ccf7155e7a">

**Comment by yoopark** [comment]
이름을 띄우기가 또 애매해서.. 새로고침하면 사진 나오니까 괜찮다고 생각했는데 인트라가 터지면 저런 식으로 나오겠군요. 어떤 방식으로 해결하면 좋을까요?

**Comment by 42sungwook** [comment]
고민중이에요,,
지금 경우는 intra사진이 두분 다 없는 경우여서 제보가 들어왔어요

둘 다 사진이 뜨지 않을 때만 이름이나 자기자신이라는 표현을 띄워주는건 어떤가요?

**Comment by yoopark** [comment]
좋은 생각이 났는데, Chakra UI Avatar 처럼 로딩에 실패하였을 때는 이니셜을 띄워주는 건 어떨까요? 
이니셜이 같으면... 그건 모르겠습니다만

Ref. https://chakra-ui.com/docs/components/avatar

**Comment by 42sungwook** [comment]
> 좋은 생각이 났는데, Avatar 컴포넌트 자체를 Chakra UI Avatar 처럼 로딩에 실패하였을 때는 이니셜을 띄워주는 건 어떨까요? 이니셜이 같으면... 그건 모르겠습니다만
> 
> Ref. https://chakra-ui.com/docs/components/avatar

이게 그나마 깔끔하게 해결할 수 있겠네요
오늘 시간날 때 봐보겠습니다

**Comment by 42sungwook** [comment]
음.. 자기 자신이랑 비교하는건데 본인 사진이 안나올때 그 사진만 ME라고 표기하는건 어떤가요?

**Comment by yoopark** [comment]
> 음.. 자기 자신이랑 비교하는건데 본인 사진이 안나올때 그 사진만 ME라고 표기하는건 어떤가요?

ME는 디자인이 안 예쁜 것 같습니다. Chakra UI 처럼 이름 -> 배경색을 고유하게 유지하도록 하는 알고리즘을 짜서 배경색으로도 구분되게 하는 건 어떨까요?

**Comment by 42sungwook** [comment]
알겠습니다. 이니셜 쓰려면 intraId 보다는 영어 이름을 가져와서 해야겠네여
