### ISSUE TITLE
뒤로가기할 때 스크롤이 맨 위로 이동하는 문제

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#319]
- UX 상 좋지 않다는 의견에 동감하였습니다. 
- 리더보드에 국한하자는 의견이 있었으나, 해당 코드를 빼면 홈 -> 내 정보로 이동할 때에도 scrollToTop이 먹히지 않아 전역에 적용하는 게 나을 것 같습니다. 
- **뒤로가기할 때** 스크롤이 맨 위로 이동하는게 UX에 좋지 않다고 판단하여 뒤로가기나 앞으로가기를 했을 때 스크롤을 변경하지 않는 방식이 있다면 적용해보고자 합니다.

**Comment by yoopark** [comment]
https://reactrouter.com/en/main/components/scroll-restoration   
React Router v6의 data router를 써야 지원하는 것 같은데...

history는 사라져서 쓰기가 좀 그렇다.

**Comment by 42sungwook** [comment]
페이지별로 scroll 위치를 저장하는게 맞는 것 같은데
찾아보니까 무한스크롤일 때도 고려해야되네요,,

**Comment by yoopark** [comment]
일단은 LeaderboardLayout 단에 ScrollToTop 을 거는 것으로 잠정 수정하겠습니다.
