### ISSUE TITLE
평가 로그 width 처리

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Frontend#322]
https://stat.42seoul.kr/evallog?corrector=jubae&corrected=juyyang&projectName=netpr&flag=all&sortOrder=BEGIN_AT_DESC,
https://stat.42seoul.kr/team/5111845

**Comment by 42sungwook** [comment]
dev로 보면 처리되있는 것 같아요

**Comment by yoopark** [comment]
- #273 

그때 hotfix로 고치질 않았네요. 
이번 배포 때 머지하면 될 것 같습니다!
