### ISSUE TITLE
[Fix] calculator 에서 불필요하게 personal general 호출하는 문제

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Frontend#348]
문제: 블랙홀 계산기에서 getPersonalGeneral 이 error 를 반환하는 경우, 페이지 전체가 빈 화면이 나옴

자신의 정보를 호출하는 것이 자명한 경우에는 getMyInfo 라는 endpoint 가 있습니다.
getPersonalGeneral 은 무조건 학생 계정을 조회한다는 가정 하에, 42seoul 학생이 아니면 exception 을 발생시키고,
getMyInfo 는 nullable 하게 되어 있습니다. (스태프, 해외 계정 등등이 null 반환되는 경우 입니다.)

때문에 '본인의 정보' 가 필요한 경우에는 getMyInfo 를 사용하는 것이 바람직하고,
calculator 의 경우처럼 필요한 field (level) 이 없는 경우 백엔드와 의논해야 합니다.

**Comment by yoopark** [comment]
인정합니다. 제 의견은,

1. BE `getMyInfo` 내에 level 필드를 추가한다.
2. `getMyInfo`가 null 반환되었을 때에도 블랙홀 계산기를 사용할 수 있도록 처리한다. (현재 레벨, 현재 블랙홀, 본과정 시작한지 모두 0일) 
3. useQuery 자체가 error일 때에는 getExpTable을 가져오지 못하므로 ApolloFullPageErrorView를 띄운다. (getExpTable에는 fetch error가 안 나는데 getMyInfo에서 fetch error가 나는 경우가 딱히 없을 것 같아서 useQuery를 두개로 분리할 필요는 없다고 생각합니다.)

이렇게 진행하면 될 것 같습니다!

**Comment by jpham005** [comment]
네 말씀하신대로 진행하면 될 것 같네요. 백엔드도 이슈 열고 진행하겠습니다.

**Comment by 42sungwook** [comment]
getMyInfo에 beginAt도 추가해주실 수 있나요?

**Comment by jpham005** [comment]
확인했습니다.
