### ISSUE TITLE
유저프로필 작성 고민사항

### ISSUE THREAD

**Issue by lev-Zero** [42Statistics/42Stat-Frontend#35]
1. 멤버는 어떻게 판단하나 ?
2. 레벨은 소수점까지 표현해야 하지 않을까?
3. 칭호가 길경우 호버해서 풀칭호 보이게 하나?

**Comment by yoopark** [comment]
1. GraphQL에 Enum 형식으로 오긴 하는 거 같은데 아직은 안 오네요. 
2. 지금은 12.6레벨이면 12레벨에 0.6만큼의 바로 표현하고 있는데 가독성이 떨어지나요?
3. 너무 긴 칭호의 경우 일단 ... 으로 바꿔놓았습니다. 호버했을 때 풀칭호가 깔끔하게 보이는 방식은 아직 생각을 못하겠어요

**Comment by lev-Zero** [comment]
RE
1. 지금 오는 ENUM 스키마 자체가 없는건가요 아니면 있는데 값이없는건가요 ? DOCS 상에서 뭐가 멤버인지 판단하는 키인지 모르겠습니다.

2. 경험치 바를 의미한다는 직관성이 좀 떨어지는거같고 아니면 마우스를 올렸을때 경험치와 레벨이 다뜨면 괜찮을거같기도 합니다

**Comment by yoopark** [comment]
스키마는 있습니다. 
![image](https://user-images.githubusercontent.com/61629480/229963392-98dac6e0-cd2e-406d-ab2c-f47bf4a56b8e.png)

마우스를 올렸을 때 뜬다는게 위에 popover 느낌으로 띄운다는 말씀이신가요? 깔끔하게 만들면 좋긴 한데 쉽지 않을 것 같아 아직 생각 안했습니다. 만약 만드실 예정이라면 일반화 가능하도록 잘 만드셔야 할 거 같습니다. 
```
<Popover hover={<p>{level}</p>}>
   <LevelBar />
</Popover>
```

대강 이런 식으로 사용이 가능해야 합니다.
