### ISSUE TITLE
Router Error

### ISSUE THREAD

**Issue by 42sungwook** [42Statistics/42Stat-Frontend#350]
#346 react router v6.4 도입하면서 spotlight가 고장났습니다
<img width="1060" alt="스크린샷 2023-10-24 오후 12 09 27" src="https://github.com/42Statistics/42Stat-Frontend/assets/106149304/6b6f6c44-cf71-4b7f-9f65-3eb348402934">

**Comment by yoopark** [comment]
아하... 그렇겠군요

**Comment by 42sungwook** [comment]
어… 페이지 아닌 모달같은 애들은 다 에러뜨나봐요
relogin도 에러뜨네요ㅠ
이 이슈를 빨리 처리해야될 것 같은데 오늘 볼 수 있으신가요?
아니면 제가 할까요?

<img width="830" alt="Screen Shot 2023-10-24 at 2 51 00 PM" src="https://github.com/42Statistics/42Stat-Frontend/assets/106149304/918d3f16-2a25-48bb-ab88-772e58db25d2">

**Comment by yoopark** [comment]
모달 검사를 안 해보다니..ㅋㅋ 테스트를 안 짠 제 업보군요. 개발 못하시겠구만요 죄송합니다. 😂😂😂😂 오늘 저녁에 고쳐서 올리겠습니당 시간 나면 한번 고쳐보셔도 괜찮습니다.

**Comment by 42sungwook** [comment]
한번 봐보겠습니다 ㅎㅎ
