### ISSUE TITLE
[Feat] theme에 따른 html 태그에 배경색상 적용

### ISSUE THREAD

**Issue by 42sungwook** [42Statistics/42Stat-Frontend#359]
![image](https://github.com/42Statistics/42Stat-Frontend/assets/106149304/3d6346b1-bb62-41e9-b4c6-beed18d01ad7)

상단의 색상이 다크모드일 때 불편하다는 제보가 들어와서 수정합니다

<img width="464" alt="스크린샷 2023-10-27 오후 2 18 20" src="https://github.com/42Statistics/42Stat-Frontend/assets/106149304/389b6822-d37e-4e83-aedb-ef317a153af8">

**Comment by yoopark** [comment]
ㅋㅋㅋㅋ.. 아 그거 고쳐주세요. 예전에 아무리 찾아봐도 안 나와서 🥲

**Comment by yoopark** [comment]
위 PR이 이슈를 해결하지 못했기 때문에 Reopen합니다.
