### ISSUE TITLE
[CI] 배포 시 max-age: 0 설정

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#388]
- max-age를 설정해주지 않으면 cloudfront 기본 설정인 24시간이 적용되어, 배포한 내용이 바로 반영되지 않습니다. 
- 이제까지는 cloudfront 무효화를 수동으로 해주고 있던 실정입니다. 
- 아래 링크를 참고하면 cloudfront 무효화를 커맨드로 설정해줄 수 있긴 한데, 일단 index.html 파일 헤더에 max-age: 0을 넣는 방법을 찾아보도록 하겠습니다. 

Ref. https://docs.aws.amazon.com/cli/latest/reference/cloudfront/create-invalidation.html#examples

**Comment by jpham005** [comment]
0 보다는 5분 (300) 정도 설정해주는게 좋을 것 같습니다.
0으로 하게 되면 평상시에 cache-miss 가 무조건 발생하기 때문에 별로 좋지 않아보여요.

stale-if-error 같은 값도 알아보시면 좋을 것 같습니다.
