### ISSUE TITLE
[FIX] 블랙홀 계산기 현재 레벨 입력 버그 제보

### ISSUE THREAD

**Issue by seo-wo** [42Statistics/42Stat-Frontend#440]
안녕하세요 42stat을 사용 중인 seowokim 입니다.
다름이 아니라 블랙홀 계산기에서 현재 레벨 입력 창에서 소수점 첫번째 자리에 0이 입력이 안되는 문제가 있습니다.

해당 입력을 처리하는 `/app/src/Calculator/components/CalculatorBasicInfoInputGroup/index.tsx` 입니다.
```typescript
  const handleChange: React.ChangeEventHandler<HTMLInputElement> = (e) => {
    const value = Number(e.target.value);
    if (isNaN(value) || value < 0) return;
    const name = e.target.name as keyof typeof calculatorUserInfoAtom;
    setCalculatorUserInfo((prev) => ({
      ...prev,
      [name]: value,
    }));
  };
```
예시로 11.03을 입력하고자 하면 11.0을 입력하는 순간 value는 11로 변환이 되기에 입력창에는 11.0이 표기되는것이 아닌 11이 표기가 되어서 소숫점 2번째 자리를 입력할 수 없습니다.

---

의도하신 기능인지 아닌지는 모르겠으나 혹시 몰라 제보드립니다...!
감사합니다.

**Comment by yoopark** [comment]
안녕하세요! 42Stat을 잘 이용해주셔서 정말 감사드립니다. 
직접 이슈와 코드 상 버그 발생 지점까지 찾아주셔서 정말 감사할 따름입니다. 

확인해본 결과 해당 내용은 버그가 맞습니다. 
유저가 입력한 문자열을 그대로 상태로 저장하여야 하는데, Number로 변환 후 상태로 저장하여 버그가 발생하는 것으로 생각합니다. 
해당 내용 개발하신 @42sungwook 님이 맡아서 해결해주실 겁니다 😄

**Comment by 42sungwook** [comment]
버그 확인했습니다. 제가 오늘 내일 일정이 있어서 바로 고치기 어려울 것 같은데 최대한 빨리 고치겠습니다! 제보 감사합니다 새해 복 많이 받으세요~~😆

**Comment by 42sungwook** [comment]
해당 버그 고쳐서 배포 완료했습니다!
