### ISSUE TITLE
이 유저를 평가자로 만난다면, 유저 포켓몬 필요한 수치 문서화

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Frontend#47]

**Comment by lev-Zero** [comment]
기준 : 노력 지표 x축, 재능 지표 y축으로 하여 좌표상 위치/원점과의 기울기/원점과의 거리를 고려하여 캐릭터 매칭

노력 지표 : 클러스터 체류시간 / 다른사람들 평균 체류시간, 평가 횟수 / 다른사람들평균 평가횟수, 
아젠다 등록 횟수 , 시험 및 과제 리트 횟수

재능 지표 : n기인 해당 유저 레벨 / n기 평균 레벨, 한번에 통과한 시험 수 / 전체 시험수, 한번에 통과한 과제수 / 전체 과제트라이수, 받은 평가 중 Outstanding의 개수 / 전체 받은평가 수
