### ISSUE TITLE
포켓몬 분포도 설계초안

### ISSUE THREAD

**Issue by lev-Zero** [42Statistics/42Stat-Frontend#9]
### **닮은 포켓몬 기획**
노력 / 재능 을 xy 축으로 해서 그래프 만들고 그 그래프 상에 캐릭터를 분포시키고 유저의 도출된 xy좌표에 가장 가까운 캐릭터를 출력하는 방식 

### **점수 산출 변인**

- 노력 - 
1. 클러스터 체류시간 
2. 재도전 횟수 
3. 평가 횟수 
4. 아젠다 등록횟수 
5. 총 시험 본 횟수 

- 재능 - 
1. 한번에 통과한 과제갯수 
2. 평균 카뎃의 과제 진행속도 대비 현재카뎃의 과제 진행속도 
3. 아웃스텐딩 갯수 
4. '한번에 통과한' 시험 갯수 

### **설명**
> 노력이 높다 → 딱딱한 타입 바위 땅 등 
> 재능이 높다 → 에스퍼 타입(머리가좋음) / 전기타입(빠름) / 고스트,악 (악마의 재능)
> 노력/재능 = 기울기별로 타입이 달라짐

노력+ 재능 다좋다 →드래곤타입
각 극한에는 전설의 포켓몬 배치

### **비고**
기수별로 포켓몬 세대와 매칭시키는것도 괜찮고 다수가 분포하는 원점 근처 부근에는 비슷한 포켓몬을 여러마리씩 배치가능
-> 일단은 하나만해서 분포도만 채우기

입교생은 스타팅 포켓몬부터 시작하는데 세대별 스타팅→기수별 / 코알리숑별로 매칭가능
(현재 포켓몬은 9세대 까지 나왔고 지금 기수는 9기)
(건곤감리별 매칭도 고려가능 - 포켓몬 스타팅은 3종류이기에 고려가 조금 필요)

휴학중인 인원 → 단데기 딱충이 쉘곤 등으로 표현가능

작업 진행은 피그마에서 할 예정입니다.

**Comment by yoopark** [comment]
https://github.com/42Statistics/42Stat-discussion/discussions/5

여기에 어제 정리하여 올렸었는데, 참고만 하시라고 링크 올려드립니당
